// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEvidenceByRisk = `-- name: CountEvidenceByRisk :many
SELECT supports_risk, COUNT(*)::bigint AS n
  FROM evidence_facts
 WHERE verification_id = $1
 GROUP BY supports_risk
 ORDER BY supports_risk
`

type CountEvidenceByRiskRow struct {
	SupportsRisk string `db:"supports_risk" json:"supports_risk"`
	N            int64  `db:"n" json:"n"`
}

func (q *Queries) CountEvidenceByRisk(ctx context.Context, verificationID pgtype.UUID) ([]CountEvidenceByRiskRow, error) {
	rows, err := q.db.Query(ctx, countEvidenceByRisk, verificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEvidenceByRiskRow{}
	for rows.Next() {
		var i CountEvidenceByRiskRow
		if err := rows.Scan(&i.SupportsRisk, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEvidenceForVerification = `-- name: DeleteEvidenceForVerification :exec
DELETE FROM evidence_facts
 WHERE verification_id = $1
`

func (q *Queries) DeleteEvidenceForVerification(ctx context.Context, verificationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvidenceForVerification, verificationID)
	return err
}

const insertEvidenceFact = `-- name: InsertEvidenceFact :one

INSERT INTO evidence_facts (
    verification_id,
    source,
    tool_name,
    fact_type,
    value,
    supports_risk,
    weight,
    citation
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, verification_id, source, tool_name, fact_type, value, supports_risk, weight, citation, fetched_at
`

type InsertEvidenceFactParams struct {
	VerificationID pgtype.UUID    `db:"verification_id" json:"verification_id"`
	Source         string         `db:"source" json:"source"`
	ToolName       string         `db:"tool_name" json:"tool_name"`
	FactType       string         `db:"fact_type" json:"fact_type"`
	Value          []byte         `db:"value" json:"value"`
	SupportsRisk   string         `db:"supports_risk" json:"supports_risk"`
	Weight         pgtype.Numeric `db:"weight" json:"weight"`
	Citation       pgtype.Text    `db:"citation" json:"citation"`
}

// Evidence facts insert + lookup.
//
// The agent writes each fact as it collects it (during the parallel
// fan-out). The web layer reads facts grouped by sub-agent (source +
// tool) to render the results page. The risk engine reads them all
// and computes the verdict.
func (q *Queries) InsertEvidenceFact(ctx context.Context, arg InsertEvidenceFactParams) (EvidenceFact, error) {
	row := q.db.QueryRow(ctx, insertEvidenceFact,
		arg.VerificationID,
		arg.Source,
		arg.ToolName,
		arg.FactType,
		arg.Value,
		arg.SupportsRisk,
		arg.Weight,
		arg.Citation,
	)
	var i EvidenceFact
	err := row.Scan(
		&i.ID,
		&i.VerificationID,
		&i.Source,
		&i.ToolName,
		&i.FactType,
		&i.Value,
		&i.SupportsRisk,
		&i.Weight,
		&i.Citation,
		&i.FetchedAt,
	)
	return i, err
}

const listEvidenceByVerification = `-- name: ListEvidenceByVerification :many
SELECT id, verification_id, source, tool_name, fact_type, value, supports_risk, weight, citation, fetched_at
  FROM evidence_facts
 WHERE verification_id = $1
 ORDER BY source ASC,
          tool_name ASC,
          fetched_at ASC
`

func (q *Queries) ListEvidenceByVerification(ctx context.Context, verificationID pgtype.UUID) ([]EvidenceFact, error) {
	rows, err := q.db.Query(ctx, listEvidenceByVerification, verificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceFact{}
	for rows.Next() {
		var i EvidenceFact
		if err := rows.Scan(
			&i.ID,
			&i.VerificationID,
			&i.Source,
			&i.ToolName,
			&i.FactType,
			&i.Value,
			&i.SupportsRisk,
			&i.Weight,
			&i.Citation,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByVerificationAndType = `-- name: ListEvidenceByVerificationAndType :many
SELECT id, verification_id, source, tool_name, fact_type, value, supports_risk, weight, citation, fetched_at
  FROM evidence_facts
 WHERE verification_id = $1
   AND fact_type       = $2
 ORDER BY fetched_at ASC
`

type ListEvidenceByVerificationAndTypeParams struct {
	VerificationID pgtype.UUID `db:"verification_id" json:"verification_id"`
	FactType       string      `db:"fact_type" json:"fact_type"`
}

func (q *Queries) ListEvidenceByVerificationAndType(ctx context.Context, arg ListEvidenceByVerificationAndTypeParams) ([]EvidenceFact, error) {
	rows, err := q.db.Query(ctx, listEvidenceByVerificationAndType, arg.VerificationID, arg.FactType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceFact{}
	for rows.Next() {
		var i EvidenceFact
		if err := rows.Scan(
			&i.ID,
			&i.VerificationID,
			&i.Source,
			&i.ToolName,
			&i.FactType,
			&i.Value,
			&i.SupportsRisk,
			&i.Weight,
			&i.Citation,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
