// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedbackByOutcome = `-- name: CountFeedbackByOutcome :many
SELECT outcome, COUNT(*)::bigint AS n
  FROM verification_feedback
 GROUP BY outcome
 ORDER BY outcome
`

type CountFeedbackByOutcomeRow struct {
	Outcome string `db:"outcome" json:"outcome"`
	N       int64  `db:"n" json:"n"`
}

func (q *Queries) CountFeedbackByOutcome(ctx context.Context) ([]CountFeedbackByOutcomeRow, error) {
	rows, err := q.db.Query(ctx, countFeedbackByOutcome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFeedbackByOutcomeRow{}
	for rows.Next() {
		var i CountFeedbackByOutcomeRow
		if err := rows.Scan(&i.Outcome, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVerificationFeedback = `-- name: InsertVerificationFeedback :one
INSERT INTO verification_feedback (verification_id, outcome, comment)
VALUES ($1, $2, $3)
RETURNING id, verification_id, outcome, comment, submitted_at
`

type InsertVerificationFeedbackParams struct {
	VerificationID pgtype.UUID `db:"verification_id" json:"verification_id"`
	Outcome        string      `db:"outcome" json:"outcome"`
	Comment        pgtype.Text `db:"comment" json:"comment"`
}

func (q *Queries) InsertVerificationFeedback(ctx context.Context, arg InsertVerificationFeedbackParams) (VerificationFeedback, error) {
	row := q.db.QueryRow(ctx, insertVerificationFeedback, arg.VerificationID, arg.Outcome, arg.Comment)
	var i VerificationFeedback
	err := row.Scan(
		&i.ID,
		&i.VerificationID,
		&i.Outcome,
		&i.Comment,
		&i.SubmittedAt,
	)
	return i, err
}

const listPendingScamFeedback = `-- name: ListPendingScamFeedback :many
SELECT vf.id, vf.verification_id, vf.comment, vf.submitted_at,
       v.company_name, v.claimed_address, v.recruiter_email, v.recruiter_phone
  FROM verification_feedback vf
  JOIN verifications v ON v.id = vf.verification_id
 WHERE vf.outcome = 'confirmed_scam'
 ORDER BY vf.submitted_at ASC
 LIMIT $1
`

type ListPendingScamFeedbackRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	VerificationID pgtype.UUID        `db:"verification_id" json:"verification_id"`
	Comment        pgtype.Text        `db:"comment" json:"comment"`
	SubmittedAt    pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	CompanyName    pgtype.Text        `db:"company_name" json:"company_name"`
	ClaimedAddress pgtype.Text        `db:"claimed_address" json:"claimed_address"`
	RecruiterEmail pgtype.Text        `db:"recruiter_email" json:"recruiter_email"`
	RecruiterPhone pgtype.Text        `db:"recruiter_phone" json:"recruiter_phone"`
}

// Pending = outcome='confirmed_scam' and not yet promoted into scam_reports.
func (q *Queries) ListPendingScamFeedback(ctx context.Context, limit int32) ([]ListPendingScamFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listPendingScamFeedback, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingScamFeedbackRow{}
	for rows.Next() {
		var i ListPendingScamFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.VerificationID,
			&i.Comment,
			&i.SubmittedAt,
			&i.CompanyName,
			&i.ClaimedAddress,
			&i.RecruiterEmail,
			&i.RecruiterPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
