// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jurisdictions.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJurisdiction = `-- name: GetJurisdiction :one

SELECT code, name, recruitment_fee_legal, max_fee_pct, citation_url, updated_at
  FROM jurisdictions
 WHERE code = $1
`

// jurisdictions lookups for the mcp-law server.
func (q *Queries) GetJurisdiction(ctx context.Context, code string) (Jurisdiction, error) {
	row := q.db.QueryRow(ctx, getJurisdiction, code)
	var i Jurisdiction
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.RecruitmentFeeLegal,
		&i.MaxFeePct,
		&i.CitationUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listJurisdictions = `-- name: ListJurisdictions :many
SELECT code, name, recruitment_fee_legal, max_fee_pct, citation_url, updated_at
  FROM jurisdictions
 ORDER BY code ASC
`

func (q *Queries) ListJurisdictions(ctx context.Context) ([]Jurisdiction, error) {
	rows, err := q.db.Query(ctx, listJurisdictions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jurisdiction{}
	for rows.Next() {
		var i Jurisdiction
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.RecruitmentFeeLegal,
			&i.MaxFeePct,
			&i.CitationUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJurisdiction = `-- name: UpsertJurisdiction :exec
INSERT INTO jurisdictions (code, name, recruitment_fee_legal, max_fee_pct, citation_url, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (code) DO UPDATE
    SET name                  = EXCLUDED.name,
        recruitment_fee_legal = EXCLUDED.recruitment_fee_legal,
        max_fee_pct           = EXCLUDED.max_fee_pct,
        citation_url          = EXCLUDED.citation_url,
        updated_at            = now()
`

type UpsertJurisdictionParams struct {
	Code                string         `db:"code" json:"code"`
	Name                string         `db:"name" json:"name"`
	RecruitmentFeeLegal bool           `db:"recruitment_fee_legal" json:"recruitment_fee_legal"`
	MaxFeePct           pgtype.Numeric `db:"max_fee_pct" json:"max_fee_pct"`
	CitationUrl         string         `db:"citation_url" json:"citation_url"`
}

// Used by the periodic loader that refreshes the table from
// data/recruitment-law.json (see Phase 11).
func (q *Queries) UpsertJurisdiction(ctx context.Context, arg UpsertJurisdictionParams) error {
	_, err := q.db.Exec(ctx, upsertJurisdiction,
		arg.Code,
		arg.Name,
		arg.RecruitmentFeeLegal,
		arg.MaxFeePct,
		arg.CitationUrl,
	)
	return err
}
