// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_audit.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMCPAuditByServerToolStatus = `-- name: CountMCPAuditByServerToolStatus :many
SELECT server,
       tool,
       status,
       COUNT(*)::bigint AS n
  FROM mcp_audit_log
 WHERE called_at >= $1
 GROUP BY server, tool, status
 ORDER BY server, tool, status
`

type CountMCPAuditByServerToolStatusRow struct {
	Server string `db:"server" json:"server"`
	Tool   string `db:"tool" json:"tool"`
	Status string `db:"status" json:"status"`
	N      int64  `db:"n" json:"n"`
}

// Used by Prometheus-style introspection panels.
func (q *Queries) CountMCPAuditByServerToolStatus(ctx context.Context, calledAt pgtype.Timestamptz) ([]CountMCPAuditByServerToolStatusRow, error) {
	rows, err := q.db.Query(ctx, countMCPAuditByServerToolStatus, calledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMCPAuditByServerToolStatusRow{}
	for rows.Next() {
		var i CountMCPAuditByServerToolStatusRow
		if err := rows.Scan(
			&i.Server,
			&i.Tool,
			&i.Status,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMCPAuditLog = `-- name: InsertMCPAuditLog :exec

INSERT INTO mcp_audit_log (
    verification_id,
    server,
    tool,
    args_hash,
    latency_ms,
    status,
    error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertMCPAuditLogParams struct {
	VerificationID pgtype.UUID `db:"verification_id" json:"verification_id"`
	Server         string      `db:"server" json:"server"`
	Tool           string      `db:"tool" json:"tool"`
	ArgsHash       string      `db:"args_hash" json:"args_hash"`
	LatencyMs      int32       `db:"latency_ms" json:"latency_ms"`
	Status         string      `db:"status" json:"status"`
	Error          pgtype.Text `db:"error" json:"error"`
}

// Append-only writes plus a few read paths used by the observability
// subsystem (Phase 18) and the replay tooling.
func (q *Queries) InsertMCPAuditLog(ctx context.Context, arg InsertMCPAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertMCPAuditLog,
		arg.VerificationID,
		arg.Server,
		arg.Tool,
		arg.ArgsHash,
		arg.LatencyMs,
		arg.Status,
		arg.Error,
	)
	return err
}

const listMCPAuditByVerification = `-- name: ListMCPAuditByVerification :many
SELECT id, verification_id, server, tool, args_hash, latency_ms, status, error, called_at
  FROM mcp_audit_log
 WHERE verification_id = $1
 ORDER BY called_at ASC
`

func (q *Queries) ListMCPAuditByVerification(ctx context.Context, verificationID pgtype.UUID) ([]McpAuditLog, error) {
	rows, err := q.db.Query(ctx, listMCPAuditByVerification, verificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpAuditLog{}
	for rows.Next() {
		var i McpAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.VerificationID,
			&i.Server,
			&i.Tool,
			&i.ArgsHash,
			&i.LatencyMs,
			&i.Status,
			&i.Error,
			&i.CalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
