// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package joblanterndb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type EvidenceFact struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	VerificationID pgtype.UUID        `db:"verification_id" json:"verification_id"`
	Source         string             `db:"source" json:"source"`
	ToolName       string             `db:"tool_name" json:"tool_name"`
	FactType       string             `db:"fact_type" json:"fact_type"`
	Value          []byte             `db:"value" json:"value"`
	SupportsRisk   string             `db:"supports_risk" json:"supports_risk"`
	Weight         pgtype.Numeric     `db:"weight" json:"weight"`
	Citation       pgtype.Text        `db:"citation" json:"citation"`
	FetchedAt      pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

type FederatedPeer struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Url        string             `db:"url" json:"url"`
	Name       string             `db:"name" json:"name"`
	Pubkey     string             `db:"pubkey" json:"pubkey"`
	TrustLevel string             `db:"trust_level" json:"trust_level"`
	LastSeen   pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Jurisdiction struct {
	Code                string             `db:"code" json:"code"`
	Name                string             `db:"name" json:"name"`
	RecruitmentFeeLegal bool               `db:"recruitment_fee_legal" json:"recruitment_fee_legal"`
	MaxFeePct           pgtype.Numeric     `db:"max_fee_pct" json:"max_fee_pct"`
	CitationUrl         string             `db:"citation_url" json:"citation_url"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type McpAuditLog struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	VerificationID pgtype.UUID        `db:"verification_id" json:"verification_id"`
	Server         string             `db:"server" json:"server"`
	Tool           string             `db:"tool" json:"tool"`
	ArgsHash       string             `db:"args_hash" json:"args_hash"`
	LatencyMs      int32              `db:"latency_ms" json:"latency_ms"`
	Status         string             `db:"status" json:"status"`
	Error          pgtype.Text        `db:"error" json:"error"`
	CalledAt       pgtype.Timestamptz `db:"called_at" json:"called_at"`
}

type Plugin struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Version     string             `db:"version" json:"version"`
	License     string             `db:"license" json:"license"`
	Trust       string             `db:"trust" json:"trust"`
	Manifest    string             `db:"manifest" json:"manifest"`
	SourceUrl   pgtype.Text        `db:"source_url" json:"source_url"`
	Enabled     bool               `db:"enabled" json:"enabled"`
	InstalledAt pgtype.Timestamptz `db:"installed_at" json:"installed_at"`
}

type ScamReport struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyName  pgtype.Text        `db:"company_name" json:"company_name"`
	Address      pgtype.Text        `db:"address" json:"address"`
	AddressGeom  interface{}        `db:"address_geom" json:"address_geom"`
	Phone        pgtype.Text        `db:"phone" json:"phone"`
	Email        pgtype.Text        `db:"email" json:"email"`
	Domain       pgtype.Text        `db:"domain" json:"domain"`
	ReportSource pgtype.Text        `db:"report_source" json:"report_source"`
	ReportUrl    pgtype.Text        `db:"report_url" json:"report_url"`
	Summary      pgtype.Text        `db:"summary" json:"summary"`
	Embedding    pgvector.Vector    `db:"embedding" json:"embedding"`
	ReportedAt   pgtype.Timestamptz `db:"reported_at" json:"reported_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Verification struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	RawInput       []byte             `db:"raw_input" json:"raw_input"`
	ListingUrl     pgtype.Text        `db:"listing_url" json:"listing_url"`
	RecruiterEmail pgtype.Text        `db:"recruiter_email" json:"recruiter_email"`
	RecruiterPhone pgtype.Text        `db:"recruiter_phone" json:"recruiter_phone"`
	CompanyName    pgtype.Text        `db:"company_name" json:"company_name"`
	ClaimedAddress pgtype.Text        `db:"claimed_address" json:"claimed_address"`
	ClaimedSalary  pgtype.Numeric     `db:"claimed_salary" json:"claimed_salary"`
	Role           pgtype.Text        `db:"role" json:"role"`
	Jurisdiction   pgtype.Text        `db:"jurisdiction" json:"jurisdiction"`
	Status         string             `db:"status" json:"status"`
	OverallRisk    pgtype.Text        `db:"overall_risk" json:"overall_risk"`
	Confidence     pgtype.Numeric     `db:"confidence" json:"confidence"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ClaimedGeom    interface{}        `db:"claimed_geom" json:"claimed_geom"`
}

type VerificationFeedback struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	VerificationID pgtype.UUID        `db:"verification_id" json:"verification_id"`
	Outcome        string             `db:"outcome" json:"outcome"`
	Comment        pgtype.Text        `db:"comment" json:"comment"`
	SubmittedAt    pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
}
