// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteVerification(ctx context.Context, arg CompleteVerificationParams) error
	CountEvidenceByRisk(ctx context.Context, verificationID pgtype.UUID) ([]CountEvidenceByRiskRow, error)
	CountFeedbackByOutcome(ctx context.Context) ([]CountFeedbackByOutcomeRow, error)
	// Used by Prometheus-style introspection panels.
	CountMCPAuditByServerToolStatus(ctx context.Context, calledAt pgtype.Timestamptz) ([]CountMCPAuditByServerToolStatusRow, error)
	// Faster path when the caller only needs density, not the rows.
	CountScamReportsNearPoint(ctx context.Context, arg CountScamReportsNearPointParams) (int64, error)
	// CRUD for the verifications table. Consumed by:
	//   * cmd/joblantern's web layer (submit, fetch, list)
	//   * internal/agent (read while running, update on completion)
	//
	// claimed_geom is written via ST_SetSRID(ST_MakePoint(lon,lat),4326)::geography
	// in the query rather than asking sqlc to model PostGIS types. NULL is
	// written when the agent has not yet geocoded the address.
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error)
	DeleteEvidenceForVerification(ctx context.Context, verificationID pgtype.UUID) error
	DeleteVerification(ctx context.Context, id pgtype.UUID) error
	FailVerification(ctx context.Context, id pgtype.UUID) error
	// jurisdictions lookups for the mcp-law server.
	GetJurisdiction(ctx context.Context, code string) (Jurisdiction, error)
	GetVerification(ctx context.Context, id pgtype.UUID) (Verification, error)
	// Evidence facts insert + lookup.
	//
	// The agent writes each fact as it collects it (during the parallel
	// fan-out). The web layer reads facts grouped by sub-agent (source +
	// tool) to render the results page. The risk engine reads them all
	// and computes the verdict.
	InsertEvidenceFact(ctx context.Context, arg InsertEvidenceFactParams) (EvidenceFact, error)
	// Append-only writes plus a few read paths used by the observability
	// subsystem (Phase 18) and the replay tooling.
	InsertMCPAuditLog(ctx context.Context, arg InsertMCPAuditLogParams) error
	InsertVerificationFeedback(ctx context.Context, arg InsertVerificationFeedbackParams) (VerificationFeedback, error)
	ListEvidenceByVerification(ctx context.Context, verificationID pgtype.UUID) ([]EvidenceFact, error)
	ListEvidenceByVerificationAndType(ctx context.Context, arg ListEvidenceByVerificationAndTypeParams) ([]EvidenceFact, error)
	ListJurisdictions(ctx context.Context) ([]Jurisdiction, error)
	ListMCPAuditByVerification(ctx context.Context, verificationID pgtype.UUID) ([]McpAuditLog, error)
	// Pending = outcome='confirmed_scam' and not yet promoted into scam_reports.
	ListPendingScamFeedback(ctx context.Context, limit int32) ([]ListPendingScamFeedbackRow, error)
	ListRecentVerifications(ctx context.Context, limit int32) ([]Verification, error)
	ListVerificationsByUser(ctx context.Context, arg ListVerificationsByUserParams) ([]Verification, error)
	// pg_trgm similarity. Threshold is provided by the caller so the agent
	// can sweep from strict (0.6) to loose (0.3) progressively.
	SearchScamReportsByCompanyName(ctx context.Context, arg SearchScamReportsByCompanyNameParams) ([]SearchScamReportsByCompanyNameRow, error)
	// Match the exact domain OR any subdomain of it.
	SearchScamReportsByDomain(ctx context.Context, arg SearchScamReportsByDomainParams) ([]ScamReport, error)
	SearchScamReportsByEmail(ctx context.Context, arg SearchScamReportsByEmailParams) ([]ScamReport, error)
	// Match all reports whose email belongs to a given domain (e.g. catch
	// "joe@acme.test" and "abuse@acme.test" with input "acme.test").
	SearchScamReportsByEmailDomain(ctx context.Context, arg SearchScamReportsByEmailDomainParams) ([]ScamReport, error)
	// Cosine distance over the HNSW index. Lower distance = more similar.
	// The embedding is passed as a pgvector string literal ("[0.1,0.2,...]")
	// — sqlc treats it as text and pgvector parses it on the server side.
	SearchScamReportsByEmbedding(ctx context.Context, arg SearchScamReportsByEmbeddingParams) ([]SearchScamReportsByEmbeddingRow, error)
	// Non-spatial scam_reports lookups (phone, email, domain, name).
	// Spatial and semantic searches live in queries/scam_reports_spatial.sql.
	// Phones are normalised to E.164 by the caller before insert and before
	// search; the equality check here is exact.
	SearchScamReportsByPhone(ctx context.Context, arg SearchScamReportsByPhoneParams) ([]ScamReport, error)
	// Spatial and semantic scam_reports lookups.
	//
	// Used by mcp-scam-db to expose:
	//   * search_reports_near_point — "how many known-bad reports are
	//     within R metres of this address?"
	//   * semantic_search           — "which existing reports most
	//     resemble this freeform recruiter message?"
	// @lon, @lat are WGS84; @radius_m is metres. Geography type makes
	// ST_DWithin's third argument metres natively.
	SearchScamReportsNearPoint(ctx context.Context, arg SearchScamReportsNearPointParams) ([]SearchScamReportsNearPointRow, error)
	SetVerificationGeom(ctx context.Context, arg SetVerificationGeomParams) error
	SetVerificationRunning(ctx context.Context, id pgtype.UUID) error
	// Used by the periodic loader that refreshes the table from
	// data/recruitment-law.json (see Phase 11).
	UpsertJurisdiction(ctx context.Context, arg UpsertJurisdictionParams) error
}

var _ Querier = (*Queries)(nil)
