// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scam_reports_spatial.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countScamReportsNearPoint = `-- name: CountScamReportsNearPoint :one
SELECT COUNT(*)::bigint AS n
  FROM scam_reports
 WHERE address_geom IS NOT NULL
   AND ST_DWithin(
           address_geom,
           ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
           $3::float8
       )
`

type CountScamReportsNearPointParams struct {
	Lon     float64 `db:"lon" json:"lon"`
	Lat     float64 `db:"lat" json:"lat"`
	RadiusM float64 `db:"radius_m" json:"radius_m"`
}

// Faster path when the caller only needs density, not the rows.
func (q *Queries) CountScamReportsNearPoint(ctx context.Context, arg CountScamReportsNearPointParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScamReportsNearPoint, arg.Lon, arg.Lat, arg.RadiusM)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const searchScamReportsByEmbedding = `-- name: SearchScamReportsByEmbedding :many
SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at,
       (embedding <=> $1::vector) AS cosine_distance
  FROM scam_reports
 WHERE embedding IS NOT NULL
 ORDER BY embedding <=> $1::vector
 LIMIT $2::int
`

type SearchScamReportsByEmbeddingParams struct {
	Needle pgtype.Text `db:"needle" json:"needle"`
	Lim    int32       `db:"lim" json:"lim"`
}

type SearchScamReportsByEmbeddingRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	CompanyName    pgtype.Text        `db:"company_name" json:"company_name"`
	Address        pgtype.Text        `db:"address" json:"address"`
	AddressGeom    interface{}        `db:"address_geom" json:"address_geom"`
	Phone          pgtype.Text        `db:"phone" json:"phone"`
	Email          pgtype.Text        `db:"email" json:"email"`
	Domain         pgtype.Text        `db:"domain" json:"domain"`
	ReportSource   pgtype.Text        `db:"report_source" json:"report_source"`
	ReportUrl      pgtype.Text        `db:"report_url" json:"report_url"`
	Summary        pgtype.Text        `db:"summary" json:"summary"`
	Embedding      pgvector.Vector    `db:"embedding" json:"embedding"`
	ReportedAt     pgtype.Timestamptz `db:"reported_at" json:"reported_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CosineDistance interface{}        `db:"cosine_distance" json:"cosine_distance"`
}

// Cosine distance over the HNSW index. Lower distance = more similar.
// The embedding is passed as a pgvector string literal ("[0.1,0.2,...]")
// — sqlc treats it as text and pgvector parses it on the server side.
func (q *Queries) SearchScamReportsByEmbedding(ctx context.Context, arg SearchScamReportsByEmbeddingParams) ([]SearchScamReportsByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByEmbedding, arg.Needle, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchScamReportsByEmbeddingRow{}
	for rows.Next() {
		var i SearchScamReportsByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.CosineDistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScamReportsNearPoint = `-- name: SearchScamReportsNearPoint :many

SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at,
       ST_Distance(
           address_geom,
           ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
       ) AS distance_m
  FROM scam_reports
 WHERE address_geom IS NOT NULL
   AND ST_DWithin(
           address_geom,
           ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
           $3::float8
       )
 ORDER BY distance_m ASC
 LIMIT $4::int
`

type SearchScamReportsNearPointParams struct {
	Lon     float64 `db:"lon" json:"lon"`
	Lat     float64 `db:"lat" json:"lat"`
	RadiusM float64 `db:"radius_m" json:"radius_m"`
	Lim     int32   `db:"lim" json:"lim"`
}

type SearchScamReportsNearPointRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyName  pgtype.Text        `db:"company_name" json:"company_name"`
	Address      pgtype.Text        `db:"address" json:"address"`
	AddressGeom  interface{}        `db:"address_geom" json:"address_geom"`
	Phone        pgtype.Text        `db:"phone" json:"phone"`
	Email        pgtype.Text        `db:"email" json:"email"`
	Domain       pgtype.Text        `db:"domain" json:"domain"`
	ReportSource pgtype.Text        `db:"report_source" json:"report_source"`
	ReportUrl    pgtype.Text        `db:"report_url" json:"report_url"`
	Summary      pgtype.Text        `db:"summary" json:"summary"`
	Embedding    pgvector.Vector    `db:"embedding" json:"embedding"`
	ReportedAt   pgtype.Timestamptz `db:"reported_at" json:"reported_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DistanceM    interface{}        `db:"distance_m" json:"distance_m"`
}

// Spatial and semantic scam_reports lookups.
//
// Used by mcp-scam-db to expose:
//   - search_reports_near_point — "how many known-bad reports are
//     within R metres of this address?"
//   - semantic_search           — "which existing reports most
//     resemble this freeform recruiter message?"
//
// @lon, @lat are WGS84; @radius_m is metres. Geography type makes
// ST_DWithin's third argument metres natively.
func (q *Queries) SearchScamReportsNearPoint(ctx context.Context, arg SearchScamReportsNearPointParams) ([]SearchScamReportsNearPointRow, error) {
	rows, err := q.db.Query(ctx, searchScamReportsNearPoint,
		arg.Lon,
		arg.Lat,
		arg.RadiusM,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchScamReportsNearPointRow{}
	for rows.Next() {
		var i SearchScamReportsNearPointRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
