// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scam_reports_search.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const searchScamReportsByCompanyName = `-- name: SearchScamReportsByCompanyName :many
SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at,
       similarity(company_name, $1::text) AS sim
  FROM scam_reports
 WHERE company_name % $1::text
   AND similarity(company_name, $1::text) >= $2::float4
 ORDER BY sim DESC
 LIMIT $3::int
`

type SearchScamReportsByCompanyNameParams struct {
	Needle string  `db:"needle" json:"needle"`
	MinSim float32 `db:"min_sim" json:"min_sim"`
	Lim    int32   `db:"lim" json:"lim"`
}

type SearchScamReportsByCompanyNameRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyName  pgtype.Text        `db:"company_name" json:"company_name"`
	Address      pgtype.Text        `db:"address" json:"address"`
	AddressGeom  interface{}        `db:"address_geom" json:"address_geom"`
	Phone        pgtype.Text        `db:"phone" json:"phone"`
	Email        pgtype.Text        `db:"email" json:"email"`
	Domain       pgtype.Text        `db:"domain" json:"domain"`
	ReportSource pgtype.Text        `db:"report_source" json:"report_source"`
	ReportUrl    pgtype.Text        `db:"report_url" json:"report_url"`
	Summary      pgtype.Text        `db:"summary" json:"summary"`
	Embedding    pgvector.Vector    `db:"embedding" json:"embedding"`
	ReportedAt   pgtype.Timestamptz `db:"reported_at" json:"reported_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Sim          float32            `db:"sim" json:"sim"`
}

// pg_trgm similarity. Threshold is provided by the caller so the agent
// can sweep from strict (0.6) to loose (0.3) progressively.
func (q *Queries) SearchScamReportsByCompanyName(ctx context.Context, arg SearchScamReportsByCompanyNameParams) ([]SearchScamReportsByCompanyNameRow, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByCompanyName, arg.Needle, arg.MinSim, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchScamReportsByCompanyNameRow{}
	for rows.Next() {
		var i SearchScamReportsByCompanyNameRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScamReportsByDomain = `-- name: SearchScamReportsByDomain :many
SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at
  FROM scam_reports
 WHERE domain = $1
    OR domain ILIKE '%.' || $1
 ORDER BY reported_at DESC NULLS LAST
 LIMIT $2
`

type SearchScamReportsByDomainParams struct {
	Domain pgtype.Text `db:"domain" json:"domain"`
	Limit  int32       `db:"limit" json:"limit"`
}

// Match the exact domain OR any subdomain of it.
func (q *Queries) SearchScamReportsByDomain(ctx context.Context, arg SearchScamReportsByDomainParams) ([]ScamReport, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByDomain, arg.Domain, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScamReport{}
	for rows.Next() {
		var i ScamReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScamReportsByEmail = `-- name: SearchScamReportsByEmail :many
SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at
  FROM scam_reports
 WHERE email = $1
 ORDER BY reported_at DESC NULLS LAST
 LIMIT $2
`

type SearchScamReportsByEmailParams struct {
	Email pgtype.Text `db:"email" json:"email"`
	Limit int32       `db:"limit" json:"limit"`
}

func (q *Queries) SearchScamReportsByEmail(ctx context.Context, arg SearchScamReportsByEmailParams) ([]ScamReport, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByEmail, arg.Email, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScamReport{}
	for rows.Next() {
		var i ScamReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScamReportsByEmailDomain = `-- name: SearchScamReportsByEmailDomain :many
SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at
  FROM scam_reports
 WHERE email ILIKE '%@' || $1
 ORDER BY reported_at DESC NULLS LAST
 LIMIT $2
`

type SearchScamReportsByEmailDomainParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
}

// Match all reports whose email belongs to a given domain (e.g. catch
// "joe@acme.test" and "abuse@acme.test" with input "acme.test").
func (q *Queries) SearchScamReportsByEmailDomain(ctx context.Context, arg SearchScamReportsByEmailDomainParams) ([]ScamReport, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByEmailDomain, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScamReport{}
	for rows.Next() {
		var i ScamReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchScamReportsByPhone = `-- name: SearchScamReportsByPhone :many

SELECT id, company_name, address, address_geom, phone, email, domain, report_source, report_url, summary, embedding, reported_at, created_at
  FROM scam_reports
 WHERE phone = $1
 ORDER BY reported_at DESC NULLS LAST
 LIMIT $2
`

type SearchScamReportsByPhoneParams struct {
	Phone pgtype.Text `db:"phone" json:"phone"`
	Limit int32       `db:"limit" json:"limit"`
}

// Non-spatial scam_reports lookups (phone, email, domain, name).
// Spatial and semantic searches live in queries/scam_reports_spatial.sql.
// Phones are normalised to E.164 by the caller before insert and before
// search; the equality check here is exact.
func (q *Queries) SearchScamReportsByPhone(ctx context.Context, arg SearchScamReportsByPhoneParams) ([]ScamReport, error) {
	rows, err := q.db.Query(ctx, searchScamReportsByPhone, arg.Phone, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScamReport{}
	for rows.Next() {
		var i ScamReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Address,
			&i.AddressGeom,
			&i.Phone,
			&i.Email,
			&i.Domain,
			&i.ReportSource,
			&i.ReportUrl,
			&i.Summary,
			&i.Embedding,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
