// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package joblanterndb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeVerification = `-- name: CompleteVerification :exec
UPDATE verifications
   SET status        = 'completed',
       overall_risk  = $2,
       confidence    = $3,
       completed_at  = now()
 WHERE id = $1
`

type CompleteVerificationParams struct {
	ID          pgtype.UUID    `db:"id" json:"id"`
	OverallRisk pgtype.Text    `db:"overall_risk" json:"overall_risk"`
	Confidence  pgtype.Numeric `db:"confidence" json:"confidence"`
}

func (q *Queries) CompleteVerification(ctx context.Context, arg CompleteVerificationParams) error {
	_, err := q.db.Exec(ctx, completeVerification, arg.ID, arg.OverallRisk, arg.Confidence)
	return err
}

const createVerification = `-- name: CreateVerification :one

INSERT INTO verifications (
    user_id,
    raw_input,
    listing_url,
    recruiter_email,
    recruiter_phone,
    company_name,
    claimed_address,
    claimed_salary,
    role,
    jurisdiction
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, raw_input, listing_url, recruiter_email, recruiter_phone, company_name, claimed_address, claimed_salary, role, jurisdiction, status, overall_risk, confidence, created_at, completed_at, claimed_geom
`

type CreateVerificationParams struct {
	UserID         pgtype.UUID    `db:"user_id" json:"user_id"`
	RawInput       []byte         `db:"raw_input" json:"raw_input"`
	ListingUrl     pgtype.Text    `db:"listing_url" json:"listing_url"`
	RecruiterEmail pgtype.Text    `db:"recruiter_email" json:"recruiter_email"`
	RecruiterPhone pgtype.Text    `db:"recruiter_phone" json:"recruiter_phone"`
	CompanyName    pgtype.Text    `db:"company_name" json:"company_name"`
	ClaimedAddress pgtype.Text    `db:"claimed_address" json:"claimed_address"`
	ClaimedSalary  pgtype.Numeric `db:"claimed_salary" json:"claimed_salary"`
	Role           pgtype.Text    `db:"role" json:"role"`
	Jurisdiction   pgtype.Text    `db:"jurisdiction" json:"jurisdiction"`
}

// CRUD for the verifications table. Consumed by:
//   - cmd/joblantern's web layer (submit, fetch, list)
//   - internal/agent (read while running, update on completion)
//
// claimed_geom is written via ST_SetSRID(ST_MakePoint(lon,lat),4326)::geography
// in the query rather than asking sqlc to model PostGIS types. NULL is
// written when the agent has not yet geocoded the address.
func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.UserID,
		arg.RawInput,
		arg.ListingUrl,
		arg.RecruiterEmail,
		arg.RecruiterPhone,
		arg.CompanyName,
		arg.ClaimedAddress,
		arg.ClaimedSalary,
		arg.Role,
		arg.Jurisdiction,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawInput,
		&i.ListingUrl,
		&i.RecruiterEmail,
		&i.RecruiterPhone,
		&i.CompanyName,
		&i.ClaimedAddress,
		&i.ClaimedSalary,
		&i.Role,
		&i.Jurisdiction,
		&i.Status,
		&i.OverallRisk,
		&i.Confidence,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ClaimedGeom,
	)
	return i, err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verifications
 WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const failVerification = `-- name: FailVerification :exec
UPDATE verifications
   SET status       = 'failed',
       completed_at = now()
 WHERE id = $1
`

func (q *Queries) FailVerification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failVerification, id)
	return err
}

const getVerification = `-- name: GetVerification :one
SELECT id, user_id, raw_input, listing_url, recruiter_email, recruiter_phone, company_name, claimed_address, claimed_salary, role, jurisdiction, status, overall_risk, confidence, created_at, completed_at, claimed_geom
  FROM verifications
 WHERE id = $1
`

func (q *Queries) GetVerification(ctx context.Context, id pgtype.UUID) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerification, id)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawInput,
		&i.ListingUrl,
		&i.RecruiterEmail,
		&i.RecruiterPhone,
		&i.CompanyName,
		&i.ClaimedAddress,
		&i.ClaimedSalary,
		&i.Role,
		&i.Jurisdiction,
		&i.Status,
		&i.OverallRisk,
		&i.Confidence,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ClaimedGeom,
	)
	return i, err
}

const listRecentVerifications = `-- name: ListRecentVerifications :many
SELECT id, user_id, raw_input, listing_url, recruiter_email, recruiter_phone, company_name, claimed_address, claimed_salary, role, jurisdiction, status, overall_risk, confidence, created_at, completed_at, claimed_geom
  FROM verifications
 ORDER BY created_at DESC
 LIMIT $1
`

func (q *Queries) ListRecentVerifications(ctx context.Context, limit int32) ([]Verification, error) {
	rows, err := q.db.Query(ctx, listRecentVerifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verification{}
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawInput,
			&i.ListingUrl,
			&i.RecruiterEmail,
			&i.RecruiterPhone,
			&i.CompanyName,
			&i.ClaimedAddress,
			&i.ClaimedSalary,
			&i.Role,
			&i.Jurisdiction,
			&i.Status,
			&i.OverallRisk,
			&i.Confidence,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ClaimedGeom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationsByUser = `-- name: ListVerificationsByUser :many
SELECT id, user_id, raw_input, listing_url, recruiter_email, recruiter_phone, company_name, claimed_address, claimed_salary, role, jurisdiction, status, overall_risk, confidence, created_at, completed_at, claimed_geom
  FROM verifications
 WHERE user_id = $1
 ORDER BY created_at DESC
 LIMIT $2
 OFFSET $3
`

type ListVerificationsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListVerificationsByUser(ctx context.Context, arg ListVerificationsByUserParams) ([]Verification, error) {
	rows, err := q.db.Query(ctx, listVerificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verification{}
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawInput,
			&i.ListingUrl,
			&i.RecruiterEmail,
			&i.RecruiterPhone,
			&i.CompanyName,
			&i.ClaimedAddress,
			&i.ClaimedSalary,
			&i.Role,
			&i.Jurisdiction,
			&i.Status,
			&i.OverallRisk,
			&i.Confidence,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ClaimedGeom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVerificationGeom = `-- name: SetVerificationGeom :exec
UPDATE verifications
   SET claimed_geom = ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
 WHERE id = $3
`

type SetVerificationGeomParams struct {
	Lon float64     `db:"lon" json:"lon"`
	Lat float64     `db:"lat" json:"lat"`
	ID  pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetVerificationGeom(ctx context.Context, arg SetVerificationGeomParams) error {
	_, err := q.db.Exec(ctx, setVerificationGeom, arg.Lon, arg.Lat, arg.ID)
	return err
}

const setVerificationRunning = `-- name: SetVerificationRunning :exec
UPDATE verifications
   SET status = 'running'
 WHERE id = $1
   AND status = 'pending'
`

func (q *Queries) SetVerificationRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setVerificationRunning, id)
	return err
}
